apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ingress
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ingress
    app.kubernetes.io/part-of: ingress
  name: ingress
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: ingress
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: ingress
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-devprod-tenant/ingress/ingress@sha256:ac0af8ff24242fb0c9158c6f188085a7f15abd603f5ea167bf970bfd085c66de
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
